# Copyright (c) 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

language: python
python:
  - "2.7_with_system_site_packages"

dist:
  - xenial

# command to install dependencies
install:
  - pip install tox-travis
  - pip install -r test-requirements.txt

# command to run tests
script: tox

after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION

before_deploy:
  - sudo apt-get install python-setuptools python-all debhelper fakeroot
  - sudo pip install stdeb
  - export PYTHONPATH=/usr/local/lib/python2.7/dist-packages; python setup.py --command-packages=stdeb.command bdist_deb

deploy:
  - provider: pypi
    user: vmware_column
    password:
      secure: "MAHFyKpuUb5M9nYcqhc65SmCxC1GgFDKmYcNyoqeOqQBl3XG4/uvYxQkQ2h0RRZfMJiyNGE2fKKQSeXoavMrijDGitiiZ8IXkydP8hbNsanCL/kj0E/3MGXgIi08mOUUiKVuIn3zcDsqHUQgdRbwnMvHRVNrmeTifWwp9CrXQB0364I9CnW74O/yRJ6zewwrRKBN/xm1kWX4vyAmHvae59XcA70ViSnfqEYRKGrAZn10r7875HFRpfDHIbG8KawDKsZW0yAWkoRutSRoJ0HyyeTMptdJoEhx7Egze/sI7vy+a9i1SQ1M2FNQX1BXCPaNhO+som7QYzfY0FySGWzDVrkjCU4CDPM/1YSC42XLiG0QFilmy++OnhpAX+jMyWfxkjzw2ezou+5Y7X878Ga9pjYUA+8ceQemyhauWu0UlmYgli/cqldJ+Ac21Gtq2P/Pfor4RDE4GzTo1/rMgDow5Ly+UvE0dDlmeYed/n6jQH6uXWDSyJSVNVYcEKQw33A8kBX7KyjamU1rDtcvZGgGoajiXcb7KSjrX5IhxUNChadiriaQx4zRMNv5/4kFxXYTocR0xPguBe+Mo/50Fl72/Q4oVTXrdFsYBTX7R9QZebAYfSZRTMXvcn83M4M3IBknBpnIl4BF689lLnK30egzFTUOo6HTbNbVZrSAqdCSPys="
    distributions: sdist bdist_wheel
    skip_upload_docs: true
    skip_cleanup: true
    on:
      repo: vmware/column
      tags: true

  - provider: releases
    api_key:
      secure: "F1Rh+k0+j/o3VWxqEwBQ+9KvVennCY8vx9iqShyV4eBwvDWdytG1Rz54bcENGvzoTmaOvI0nwE2TakSRIFejCUMImvsfnWMAhzSrTPlw8O5kIEdCt1l3K4EP5WtK0i2In2DU94fva+zE54XAWPV3JFbzyH+tiL8wPYjO/3gT7UW8gd3nliEq+reOqs/WulHH/oHVLSMsWiMFeYyFZvuGMM91AzLEEEGCCstWHKPZwTXktgzO+QBQry1UeEJ4hgPEh6t9OA7LpwA4fE3GLvOz86lzG7Gf9LypvuvwWMDqD0GYFmQ9zlszSbvabErj6i/53LSiuoXTLfdVZuKP1TYGLDPthuVCDHJ2w8Bo69cihQXzBEkumgipPT0I81j3Kbi9iDRlpiCx8hJWzVpT9wQSjtET16UFpp1tNasyzmc7fTaXqRJMxHpEq5dXv4Lo0iovN9Jw1/3X9jQsrbl9BIhu7OH90jsK220ukp5xsU4Xb+HIpZJOj+6Ms0gK/2UtBxcHx0++n7HrUt0cZjiNcZhPrivSczS4qg5g9b4ezm7UZ6i6Ped6+Ld5JI1yokjkth8ATtvmcot+Vqee5dpQPOIvyqjKCdmqAlhOEFBfTmh8rRQgL5n64HgGOdXDR2nehxBMxS6uKKT5tZmsd7Oc/iVb72EeZkCUb6O7DeyKCtJh7w8="
    file_glob: true
    file:
      - dist/column*.whl
      - deb_dist/python-column*.deb
    skip_cleanup: true
    on:
      repo: vmware/column
      tags: true
